DROP TABLE IF EXISTS TRUL200_EDIT_RULES;

CREATE TABLE TRUL200_EDIT_RULES (    
    RULE_NUMBER 	INTEGER   AUTO_INCREMENT PRIMARY KEY,
    RULE_DEFINITION VARCHAR (1000),
    DROOLS_RULE 	VARCHAR (1000),
    DATE        	DATETIME DEFAULT CURRENT_TIMESTAMP
);

/*Insert INTO TRUL200_EDIT_RULES( RULE_DEFINITION, DROOLS_RULE, DATE )
VALUES ('Test Rule Definition', 'Test Rule Definition - Drools converted',CURRENT_TIMESTAMP);*/